name: Apache Pekko Site
permissions: read-all
on:
  pull_request:
    branches: ['**']
jobs:
  sbt:
    name: Check content folder
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 0
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Paradox
        run: |-
          sbt clean paradox
      - name: Git diff
        run: |-
          git diff --no-index target/paradox/site/main/ ./content/

          if [ $? -ne 0 ]; then
            echo "The content folder differs from the sources. Please update the content folder"
            exit 1
          else
            echo "No differences detected. Success."
          fi
